language: node_js

git: 
  depth: 3
cache:
  directories:
    - node_modules
    - ~/.npm
  
node_js: 
  - '12'

script:
  - yarn build


notifications:
  email: 
    recipients:
      - adoa2705@gmail.com 
    on_success: always
    on_failure: always

deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto, :3"
  on:
    branch: master


